name: templatetest

on:
  workflow_dispatch:

jobs:

  compile:
    strategy:
      matrix:
        lambdas: ${{ fromJSON(vars.lambdas) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.lambdas }}
